name: Convert CSV to JSON

on:
  push:
    paths:
      - data/*.csv

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install csvtojson
        run: npm install -g csvtojson

      - name: Convert Cards CSV to JSON
        run: |
          csvtojson "data/Tarot Quiz - Cards.csv" > data/cards.json

      - name: Convert Questions CSV to JSON
        run: |
          csvtojson "data/Tarot Quiz - Questions.csv" > data/questions.json

      - name: Commit and Push JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/cards.json data/questions.json
          git commit -m "Auto-generate JSON from CSV"
          git push
